package Hibernate_Controll;
// Generated 08-jul-2019 23:10:16 by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class RegisterCars  implements java.io.Serializable {


     private String IDCar;
     private String Model;
     private String Brand;
     private String Style;
     private String Color;
     private String Year;

    public RegisterCars(String IDCar, String Model, String Brand, String Style, String Color, String Year) {
        this.IDCar = IDCar;
        this.Model = Model;
        this.Brand = Brand;
        this.Style = Style;
        this.Color = Color;
        this.Year = Year;
    }

    public RegisterCars() {
    }
    
    

    public String getIDCar() {
        return IDCar;
    }

    public void setIDCar(String IDCar) {
        this.IDCar = IDCar;
    }

    public String getModel() {
        return Model;
    }

    public void setModel(String Model) {
        this.Model = Model;
    }

    public String getBrand() {
        return Brand;
    }

    public void setBrand(String Brand) {
        this.Brand = Brand;
    }

    public String getStyle() {
        return Style;
    }

    public void setStyle(String Style) {
        this.Style = Style;
    }

    public String getColor() {
        return Color;
    }

    public void setColor(String Color) {
        this.Color = Color;
    }

    public String getYear() {
        return Year;
    }

    public void setYear(String Year) {
        this.Year = Year;
    }
     
     


}


