package Hibernate_Controll;
// Generated 08-jul-2019 23:10:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Salesperson generated by hbm2java
 */
public class Salesperson  implements java.io.Serializable {


     private String salesPersonKey;
     private String lastName;
     private String firstName;
     private Date hireDate;
     private BigDecimal salary;

    public Salesperson() {
    }

    public Salesperson(String salesPersonKey, String lastName, String firstName, Date hireDate, BigDecimal salary) {
       this.salesPersonKey = salesPersonKey;
       this.lastName = lastName;
       this.firstName = firstName;
       this.hireDate = hireDate;
       this.salary = salary;
    }
   
    public String getSalesPersonKey() {
        return this.salesPersonKey;
    }
    
    public void setSalesPersonKey(String salesPersonKey) {
        this.salesPersonKey = salesPersonKey;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }




}


